### ISSUE TITLE
pls help ! view the indoor in place designer

### ISSUE THREAD

**Issue by 164880X** [wrld3d/wrld-indoor-maps-api#6]
Hi,
when i open in place designer indoor icon disapper but I can see the indoor map in map designer .
How can i view the indoor in place designer ?

**Comment by thomasmacdonald** [comment]
Hi there,

Thanks for your interest in our maps!

If you would like to develop your indoor map in the Places Designer before it is published to our public maps, you can append the following to the Places Designer URL:

> https://mapdesigner.wrld3d.com/poi/latest/?coverage_tree_manifest=[web-coverage-tree-manifest-URL]

Your coverage tree manifest URL can be found in the email you recieved when your indoor map built successfully. Adding it to the Places Designer URL as above will allow you to enter your indoor map in the Places Designer.

Please get in touch if you have any futher queries.

Kind regards,
Thomas

**Comment by 164880X** [comment]
got it . thank you so much.
